# Test your FastAPI endpoints
GET http://127.0.0.1:8000/
Accept: application/json
###
GET http://127.0.0.1:8000/hello/User
Accept: application/json
###

# Sync Jira tickets (fetch from Jira API → save to MongoDB)
POST http://127.0.0.1:8000/jira/tickets/sync?max_results=10
Accept: application/json
###

# List cached Jira tickets from MongoDB
GET http://127.0.0.1:8000/jira/tickets?limit=10
Accept: application/json
###

# Trigger Prefect ETL flow (MongoDB → MariaDB)
POST http://127.0.0.1:8000/flows/jira-etl?limit=100
Accept: application/json
###
